### ISSUE TITLE
Can't $require without specifying a filename

### ISSUE THREAD

**Issue by dcsan** [vkarpov15/dookie#13]
dookie looks very useful! However, I'm having trouble wtih $require

I have a simple file like
```yaml
$require: ./Types.yml

Notes:
-
  $extend: $ChiBotLesson
  title: First Chinese Lesson!
```

but it gives the error below:

```
  server Error: Can't $require without specifying a filename
  server     at /Users/dc/dev/rikai/tutorbot/papp/server/node_modules/dookie/index.js:40:17
  server     at Generator.next (<anonymous>)
  server     at onFulfilled (/Users/dc/dev/rikai/tutorbot/papp/server/node_modules/co/index.js:65:19)
  server     at process._tickCallback (internal/process/next_tick.js:109:7) +11ms

```

I looked at the options object being passed in and it seems to be empty...

dookie options {}

otherwise the push function is working, as well as $extends

Any suggestions where to look further?
